Add error handling support for aliases
This updates command alias handling to display error messages when an
alias does not correspond to a bam command or when an aliased shell
command cannot be executed.

diff --git a/bin/bam b/bin/bam
--- a/bin/bam
+++ b/bin/bam
@@ -166,10 +166,21 @@ if [ "$?" -eq 0 ]; then
     if [ "${alias:0:1}" == "!" ]; then
       # This is a shell command
       eval set -- "${alias:1}"
-      export BAM_PREFIX && cd "$BAM_TOP_LEVEL" && exec "$@" "${args[@]}"
+      export BAM_PREFIX
+      cd "$BAM_TOP_LEVEL"
+      type -P "$1" > /dev/null 2>&1 && exec "$@" "${args[@]}"
+
+      # Error: shell command not found
+      err=$("$1" 2>&1)
+      echo "bam: fatal: while expanding alias '$command': '$1':${err#*:*:*:}" >&2
+      exit 128
     fi
     eval set -- "$alias"
-    exec bam-"$@" "${args[@]}"
+    type -P "bam-$1" > /dev/null 2>&1 && exec bam-"$@" "${args[@]}"
+
+    # Error: no bam command found for alias
+    echo "bam: error: expansion of alias '$command' failed; '$1' is not a bam command" >&2
+    exit 1
   fi
 fi
 
